# Generated by Django 3.2.9 on 2022-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='venue Owner'),
        ),
    ]
