# Generated by Django 3.2.9 on 2022-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_hoteluser_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='owner',
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='venue Owner'),
        ),
    ]
