# Generated by Django 3.2.9 on 2022-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
